openapi: 3.0.3
info:
  title: OpenDataDiscovery Adapter Contract
  version: 0.0.22
  description: OpenDataDiscovery Adapter Contract
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /entities:
    get:
      description: Provides list of available entities
      operationId: getDataEntities
      tags:
        - OpenDataDiscoveryAdapter
      parameters:
        - in: query
          name: changed_since
          schema:
            type: string
            format: date-time
          description: Get data enitites updated after changed_since date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataEntityList"
components:
  schemas:
    BaseObject:
      type: object
      properties:
        oddrn:
          type: string
          example: "//aws/123456789012/redshift/odd-redshift-adapter.c0mxpzchxkqz.us-west-2.redshift.amazonaws.com/databases/oddadapter/schemas/public/tables/event/columns/eventid"
        name:
          type: string
          example: "eventid"
        owner:
          type: string
          example: "//aws/123456789012/redshift/odd-redshift-adapter.c0mxpzchxkqz.us-west-2.redshift.amazonaws.com/databases/oddadapter/schemas/smith"
        metadata:
          type: array
          items:
            $ref: "#/components/schemas/MetadataExtension"
      required:
        - oddrn
        - name

    DataEntity:
      allOf:
        - $ref: '#/components/schemas/BaseObject'
        - type: object
          properties:
            updated_at:
              type: string
              format: date-time
              example: 2021-03-25T06:12:13.488486
            created_at:
              type: string
              format: date-time
              example: 2021-03-25T06:12:13.488486
            dataset:
              $ref: '#/components/schemas/DataSet'
            data_transformer:
              $ref: '#/components/schemas/DataTransformer'
            data_transformer_run:
              $ref: '#/components/schemas/DataTransformerRun'
            data_quality_test:
              $ref: '#/components/schemas/DataQualityTest'
            data_quality_test_run:
              $ref: '#/components/schemas/DataQualityTestRun'
            data_input:
              $ref: '#/components/schemas/DataInput'
            data_consumer:
              $ref: '#/components/schemas/DataConsumer'

    DataEntityList:
      type: object
      properties:
        data_source_oddrn:
          type: string
          example: "//aws/123456789012/redshift/odd-redshift-adapter.c0mxpzchxkqz.us-west-2.redshift.amazonaws.com/"
        items:
          type: array
          items:
            $ref: '#/components/schemas/DataEntity'

    DataSet:
      type: object
      properties:
        parent_oddrn:
          type: string
          example: "//aws/123456789012/redshift/odd-redshift-adapter.c0mxpzchxkqz.us-west-2.redshift.amazonaws.com/databases/oddadapter/schemas/smith"
        description:
          type: string
        rows_number:
          type: integer
          format: int64
          example: 0
        subtype:
          type: string
          enum:
            - DATASET_TABLE
            - DATASET_VIEW
            - DATASET_FILE
            - DATASET_FEATURE_GROUP
            - DATASET_TOPIC
            - DATASET_UNKNOWN
        field_list:
          type: array
          items:
            $ref: '#/components/schemas/DataSetField'
      required:
        - subtype
        - field_list

    DataSetFieldStat:
      type: object
      properties:
        complex_stats:
          $ref: '#/components/schemas/ComplexFieldStat'
        boolean_stats:
          $ref: '#/components/schemas/BooleanFieldStat'
        integer_stats:
          $ref: '#/components/schemas/IntegerFieldStat'
        number_stats:
          $ref: '#/components/schemas/NumberFieldStat'
        string_stats:
          $ref: '#/components/schemas/StringFieldStat'
        binary_stats:
          $ref: '#/components/schemas/BinaryFieldStat'
        datetime_stats:
          $ref: '#/components/schemas/DateTimeFieldStat'

    BooleanFieldStat:
      type: object
      properties:
        true_count:
          type: integer
          format: int64
        false_count:
          type: integer
          format: int64
        nulls_count:
          type: integer
          format: int64
      required:
        - true_count
        - false_count
        - nulls_count

    ComplexFieldStat:
      type: object
      properties:
        nulls_count:
          type: integer
          format: int64
        unique_count:
          type: integer
          format: int64
      required:
        - nulls_count
        - unique_count

    NumberFieldStat:
      type: object
      properties:
        low_value:
          type: number
        high_value:
          type: number
        mean_value:
          type: number
        median_value:
          type: number
        nulls_count:
          type: integer
          format: int64
        unique_count:
          type: integer
          format: int64
      required:
        - low_value
        - high_value
        - nulls_count
        - unique_count

    StringFieldStat:
      type: object
      properties:
        max_length:
          type: integer
        avg_length:
          type: number
        nulls_count:
          type: integer
          format: int64
        unique_count:
          type: integer
          format: int64
      required:
        - max_length
        - avg_length
        - nulls_count
        - unique_count

    BinaryFieldStat:
      type: object
      properties:
        max_length:
          type: integer
        avg_length:
          type: number
        nulls_count:
          type: integer
          format: int64
        unique_count:
          type: integer
          format: int64
      required:
        - max_length
        - avg_length
        - nulls_count
        - unique_count

    IntegerFieldStat:
      type: object
      properties:
        low_value:
          type: integer
          format: int64
        high_value:
          type: integer
          format: int64
        mean_value:
          type: integer
          format: int64
        median_value:
          type: integer
          format: int64
        nulls_count:
          type: integer
          format: int64
        unique_count:
          type: integer
          format: int64
      required:
        - low_value
        - high_value
        - nulls_count
        - unique_count

    DateTimeFieldStat:
      type: object
      properties:
        low_value:
          type: string
          format: date-time
        high_value:
          type: string
          format: date-time
        mean_value:
          type: string
          format: date-time
        median_value:
          type: string
          format: date-time
        nulls_count:
          type: integer
          format: int64
        unique_count:
          type: integer
          format: int64
      required:
        - low_value
        - high_value
        - nulls_count
        - unique_count

    DataSetField:
      allOf:
        - $ref: '#/components/schemas/BaseObject'
        - type: object
          properties:
            parent_field_oddrn:
              type: string
              example: "//aws/123456789012/redshift/odd-redshift-adapter.c0mxpzchxkqz.us-west-2.redshift.amazonaws.com/databases/oddadapter/schemas/public/tables/event"
            type:
              $ref: '#/components/schemas/DataSetFieldType'
            is_key:
              type: boolean
            is_value:
              type: boolean
            default_value:
              type: string
            description:
              type: string
            stats:
              $ref: '#/components/schemas/DataSetFieldStat'
          required:
            - type

    DataSetFieldType:
      type: object
      properties:
        type:
          type: string
          enum:
            - TYPE_STRING
            - TYPE_NUMBER
            - TYPE_INTEGER
            - TYPE_BOOLEAN
            - TYPE_CHAR
            - TYPE_DATETIME
            - TYPE_TIME
            - TYPE_STRUCT
            - TYPE_BINARY
            - TYPE_LIST
            - TYPE_MAP
            - TYPE_UNION
            - TYPE_DURATION
            - TYPE_UNKNOWN
        logical_type:
          type: string
        is_nullable:
          type: boolean
      required:
        - type
        - is_nullable

    DataTransformer:
      type: object
      properties:
        description:
          type: string
        source_code_url:
          type: string
        sql:
          type: string
        inputs:
          type: array
          items:
            type: string
        outputs:
          type: array
          items:
            type: string
        subtype:
          type: string
          enum:
            - DATATRANSFORMER_JOB
            - DATATRANSFORMER_EXPERIMENT
            - DATATRANSFORMER_ML_MODEL_TRAINING
            - DATATRANSFORMER_VIEW
            - DATATRANSFORMER_UNKNOWN
      required:
        - inputs
        - outputs
        - subtype

    DataConsumer:
      type: object
      properties:
        description:
          type: string
        inputs:
          type: array
          items:
            type: string
        subtype:
          type: string
          enum:
            - DATACONSUMER_DASHBOARD
            - DATACONSUMER_ML_MODEL
      required:
        - subtype

    DataInput:
      type: object
      properties:
        description:
          type: string
      required:
        - description


    DataQualityTest:
      type: object
      properties:
        description:
          type: string
        dataset_list:
          type: array
          items:
            type: string
        suite_url:
          type: string
        linked_url_list:
          type: array
          items:
            $ref: '#/components/schemas/LinkedUrl'
      required:
        - description
        - dataset_list

    LinkedUrl:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
      required:
        - name
        - url

    DataTransformerRun:
      type: object
      properties:
        transformer_oddrn:
          type: string
          example: "//aws/123456789012/redshift/odd-redshift-adapter.c0mxpzchxkqz.us-west-2.redshift.amazonaws.com/databases/oddadapter/schemas/public/functions/start_event"
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        status_reason:
          type: string
        status:
          type: string
          enum:
            - SUCCESS
            - FAIL
            - ABORTED
            - OTHER
      required:
        - transformer_oddrn
        - start_time
        - end_time
        - status

    DataQualityTestRun:
      type: object
      properties:
        data_quality_test_oddrn:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        status_reason:
          type: string
        status:
          type: string
          enum:
            - SUCCESS
            - FAIL
            - ABORTED
            - OTHER
      required:
        - data_quality_test_oddrn
        - start_time
        - end_time
        - status

    MetadataExtension:
      type: object
      properties:
        schema_url:
          description: "The JSON Pointer (https://tools.ietf.org/html/rfc6901) URL to the corresponding version of the schema definition for this extension"
          example: "https://raw.githubusercontent.com/opendatadiscovery/opendatadiscovery-specification/main/specification/extensions/redshift.json#/definitions/RedshiftDataSetExtension"
          type: string
          format: uri
        metadata:
          type: object
          additionalProperties: true
      required:
        - schema_url
        - metadata
