name: build
on:
  push:
    branches:
      - "main"

jobs:
  images:
    runs-on: self-hosted
    env:
      REGISTRY: 436866023604.dkr.ecr.eu-central-1.amazonaws.com
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: unfor19/install-aws-cli-action@v1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1.3.3
      - name: Build, tag and push Docker image to Amazon ECR
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.event.repository.name }}:ci-${GITHUB_SHA::6} .
          docker push ${{ env.REGISTRY }}/${{ github.event.repository.name }}:ci-${GITHUB_SHA::6}